# Variables that contain the user credentials to access Twitter API.
CONSUMER_KEY = 'SKENDHV2JU6kyHGL41Xgx0CwO'
CONSUMER_KEY_SECRET = 'SU57VHdjhaVetPZxiltTMiIUGt6L9TRfGw09befMBnamzPPKhT'
ACCESS_TOKEN = '2214590456-pIwW8b1Tdwz2JIeXNGxMA7uLPkKKFATz2CdgSDy'
ACCESS_TOKEN_SECRET = '9euCYz6woDsoNLEyrQgDMpNm5STIWNz5S1B6lU6XKpSDR'
# BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAD2GIAEAAAAAwfVNFXUhC8NUxDliLyuD1ycmM8o%3DSgPxboqA4fKA8AGvMfMbyYLrmnwagdZlqSj0eytefZk1Ou9Isk'
